services:
  db-mysql8:
    container_name: db-mysql8
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=apr_user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./.db/mysql8:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  db-redis:
    container_name: db-redis
    image: redis:latest
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=password
    ports:
      - "6379:6379"
    volumes:
      - ./.db/redis:/data
      - ./config/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
  db-postgres18:
    container_name: db-postgres18
    image: postgres:18rc1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./.db/postgres18:/var/lib/postgresql
networks:
  default:
    name: docker-net
    driver: bridge